//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAI_THI_UNG_VIEN
    {
        public BAI_THI_UNG_VIEN()
        {
            this.UNG_VIEN_TRA_LOI = new HashSet<UNG_VIEN_TRA_LOI>();
        }
    
        public Nullable<int> ID_UNG_VIEN { get; set; }
        public Nullable<int> ID_BAI_THI { get; set; }
        public Nullable<int> ID_NGUOI_DANH_GIA { get; set; }
        public string SO_DIEN_THOAI { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public string EMAIL { get; set; }
        public string VI_TRI_TUYEN_DUNG { get; set; }
        public string KET_QUA_DANH_GIA { get; set; }
        public string NOI_DUNG_DANH_GIA { get; set; }
        public string TRANG_THAI_GUI_MAIL { get; set; }
        public Nullable<System.DateTime> NGAY_GUI_MAIL { get; set; }
        public Nullable<System.DateTime> NGAY_HOAN_THANH_BAI_THI { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> ID_NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<int> ID_NGUOI_SUA { get; set; }
        public int ID { get; set; }
        public Nullable<bool> TT_XOA { get; set; }
        public string DIEM_TRAC_NGHIEM { get; set; }
        public Nullable<int> SO_CAU_TU_LUAN { get; set; }
    
        public virtual BAI_THI BAI_THI { get; set; }
        public virtual NGUOI_DANH_GIA NGUOI_DANH_GIA { get; set; }
        public virtual UNG_VIEN UNG_VIEN { get; set; }
        public virtual ICollection<UNG_VIEN_TRA_LOI> UNG_VIEN_TRA_LOI { get; set; }
    }
}
