//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHU_DE_BAI_THI
    {
        public CHU_DE_BAI_THI()
        {
            this.BAI_THI = new HashSet<BAI_THI>();
            this.CAU_HOI = new HashSet<CAU_HOI>();
        }
    
        public string TEN_CHU_DE { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> ID_NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<int> ID_NGUOI_SUA { get; set; }
        public int ID { get; set; }
        public string MA_CHU_DE { get; set; }
        public Nullable<bool> TT_XOA { get; set; }
    
        public virtual ICollection<BAI_THI> BAI_THI { get; set; }
        public virtual ICollection<CAU_HOI> CAU_HOI { get; set; }
    }
}
