//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNG_VIEN
    {
        public UNG_VIEN()
        {
            this.BAI_THI_UNG_VIEN = new HashSet<BAI_THI_UNG_VIEN>();
        }
    
        public string HO_TEN { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public string SO_DIEN_THOAI { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ID_CHU_DE_BAI_THI { get; set; }
        public Nullable<int> ID_BAI_THI { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> ID_NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<int> ID_NGUOI_SUA { get; set; }
        public int ID { get; set; }
        public Nullable<bool> TT_XOA { get; set; }
        public string MA_UNG_VIEN { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> isEnabled { get; set; }
    
        public virtual ICollection<BAI_THI_UNG_VIEN> BAI_THI_UNG_VIEN { get; set; }
    }
}
