//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNG_VIEN_TRA_LOI
    {
        public int ID { get; set; }
        public Nullable<int> ID_UNG_VIEN { get; set; }
        public Nullable<int> ID_BAI_THI_UNG_VIEN { get; set; }
        public Nullable<int> ID_BAI_THI { get; set; }
        public Nullable<int> ID_CAU_HOI { get; set; }
        public string ID_DAP_AN { get; set; }
        public string NOI_DUNG_TRA_LOI { get; set; }
        public Nullable<bool> TT_KET_QUA { get; set; }
    
        public virtual BAI_THI_UNG_VIEN BAI_THI_UNG_VIEN { get; set; }
    }
}
